# 挂载位置 e.g. topbar,global,toolbox,access,cluster,workspace,project,platformSettings
extParent: topbar
# ui的超链接名称
extTitle: Timeplus
# 扩展包描述
extDesc: "Timeplus extension"
# extEmbed若为 iframe 则嵌入，若为 link 则新窗口打开
extEmbed: link
