{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timeplus
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timeplus.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls: 
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: timeplus-appserver
            port:
              name: http
      {{- if .Values.timeplusd.ingress.enabled }}
      - path: {{ .Values.timeplusd.ingress.restPath }}
        pathType: Prefix
        backend:
          service:
            name: timeplusd-svc
            port:
              name: http-streaming
      {{- end }}
    {{ if .Values.ingress.domain }}host: {{ .Values.ingress.domain }}{{- end }}
{{- end }}
