{{- if .Values.timeplusd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: timeplusd-user-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timeplus.labels" . | nindent 4 }}
data:
  z100-admin-user.yaml: |-
    users:
      {{ .Values.timeplusd.defaultAdminUsername }}:
        access_management: 1
        default_database: default
        networks:
          ip: ::/0
        password: {{ .Values.timeplusd.defaultAdminPassword | quote }}

{{- end }}