{{- if .Values.timeplusConnector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeplus-connector
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timeplus.labels" . | nindent 4 }}
    {{- if .Values.timeplusConnector.labels }}
    {{- toYaml .Values.timeplusConnector.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "timeplus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: timeplus-connector
  template:
    metadata:
      labels:
        {{- include "timeplus.podLabels" . | nindent 8 }}
        {{- if .Values.timeplusConnector.labels }}
        {{- toYaml .Values.timeplusConnector.labels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: timeplus-connector
    spec:
      {{- dict "global" .Values.global "self" .Values.timeplusConnector | include "timeplus.nodeAssignment" | nindent 6 }}
      containers:
      - name: timeplus-connector
        image: {{ include "timeplus.fullImage" .Values.timeplusConnector }}
        {{- if .Values.timeplusConnector.imagePullPolicy }}
        imagePullPolicy: {{ .Values.timeplusConnector.imagePullPolicy }}
        {{- end }}
        env:
        - name: NEUTRON_ADDRESS
          value: timeplus-appserver:8081
        - name: WORKSPACE_ID
          value: default
        {{- if .Values.timeplusConnector.resources }}
        resources:
          {{- toYaml .Values.timeplusConnector.resources | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 4196
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
{{- end }}