{{- if .Values.timeplusd.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timeplusd
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timeplus.labels" . | nindent 4 }}
    {{- if .Values.timeplusd.labels }}
    {{- toYaml .Values.timeplusd.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.timeplusd.replicas | default 3 }}
  serviceName: timeplusd-svc
  podManagementPolicy: Parallel
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ ternary "Delete" "Retain" .Values.global.pvcDeleteOnStsDelete }}
    whenScaled: {{ ternary "Delete" "Retain" .Values.global.pvcDeleteOnStsScale }}
  selector:
    matchLabels:
      {{- include "timeplus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: timeplusd
  template:
    metadata:
      annotations:
        k8s.timeplus.io/config-sha: {{ include (print $.Template.BasePath "/timeplusd-ConfigMap.yaml") . | sha256sum }}
      labels:
        {{- include "timeplus.podLabels" . | nindent 8 }}
        {{- if .Values.timeplusd.labels }}
        {{- toYaml .Values.timeplusd.labels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: timeplusd
    spec:
      {{- dict "global" .Values.global "self" .Values.timeplusd | include "timeplus.nodeAssignment" | nindent 6 }}
      initContainers:
        - name: timeplusd-init-job
          {{- if .Values.timeplusd.initJob.resources }}
          resources:
            {{- toYaml .Values.timeplusd.initJob.resources | nindent 12 }}
          {{- end }}
          image: {{ include "timeplus.fullImage" .Values.timeplusd.initJob }}
          {{- if .Values.timeplusd.initJob.imagePullPolicy }}
          imagePullPolicy: {{ .Values.timeplusd.initJob.imagePullPolicy }}
          {{- end }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -ex
              NAMESPACE={{- .Release.Namespace }}
              cp /etc/timeplusd-sources/cluster-config.yaml /etc/timeplusd-server/config.d/z200-cluster-config.yaml
              sed -i "s/<timeplusd-name>/$HOSTNAME/g" /etc/timeplusd-server/config.d/z200-cluster-config.yaml
              sed -i "s/<timeplusd-namespace>/$NAMESPACE/g" /etc/timeplusd-server/config.d/z200-cluster-config.yaml
              replicas={{ .Values.timeplusd.replicas }}
              if [[ $replicas -eq 1 ]]; then
                QUORUM=timeplusd-0.timeplusd-svc.{{- .Release.Namespace -}}.svc.cluster.local:8464
                sed -i "s/<metadata-node-quorum>/$QUORUM/g" /etc/timeplusd-server/config.d/z200-cluster-config.yaml
              else
                QUORUM=timeplusd-0.timeplusd-svc.{{- .Release.Namespace -}}.svc.cluster.local:8464,timeplusd-1.timeplusd-svc.{{- .Release.Namespace -}}.svc.cluster.local:8464,timeplusd-2.timeplusd-svc.{{- .Release.Namespace -}}.svc.cluster.local:8464
                sed -i "s/<metadata-node-quorum>/$QUORUM/g" /etc/timeplusd-server/config.d/z200-cluster-config.yaml
              fi

          volumeMounts:
            - name: timeplusd-config
              mountPath: /etc/timeplusd-sources/cluster-config.yaml
              subPath: cluster-config.yaml
            - name: timeplusd-config-cluster
              mountPath: /etc/timeplusd-server/config.d
      containers:
      - name: timeplusd
        image: {{ include "timeplus.fullImage" .Values.timeplusd }}
        {{- if .Values.timeplusd.imagePullPolicy }}
        imagePullPolicy: {{ .Values.timeplusd.imagePullPolicy }}
        {{- end }}
        command:
          - "/entrypoint.sh"
        ports:
          - name: http-streaming
            containerPort: 3218
            protocol: TCP
          - name: http-snapshot
            containerPort: 8123
            protocol: TCP
          - name: tcp-streaming
            containerPort: 8463
            protocol: TCP
          - name: tcp-internal
            containerPort: 8464
            protocol: TCP
          - name: tcp-snapshot
            containerPort: 7587
            protocol: TCP
          - name: metrics
            containerPort: 9363
            protocol: TCP    
        {{- if .Values.timeplusd.resources }}
        resources:
          {{- toYaml .Values.timeplusd.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.timeplusd.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.timeplusd.livenessProbe | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: timeplusd-history
          mountPath: /var/lib/timeplusd
        - name: timeplusd-stream
          mountPath: /var/lib/timeplusd/nativelog
        - name: timeplusd-stream
          mountPath: /var/lib/timeplusd/metastore
        {{- if .Values.timeplusd.storage.log.enabled }}
        - name: timeplusd-log
          mountPath: /var/log/timeplusd-server
        {{- end }}
        - name: timeplusd-config
          mountPath: /etc/timeplusd-server/config.d/z100-default-config.yaml
          subPath: default-config.yaml
        - name: timeplusd-config-cluster
          mountPath: /etc/timeplusd-server/config.d/z200-cluster-config.yaml
          subPath: z200-cluster-config.yaml
        - name: timeplusd-config
          mountPath: /etc/timeplusd-server/config.d/z300-custom-config.yaml
          subPath: custom-config.yaml
        - name: timeplusd-user-config
          mountPath: /etc/timeplusd-server/users.d
      volumes:
      - name: timeplusd-config-cluster
        emptyDir: {}
      - name: timeplusd-config
        configMap:
          name: timeplusd-config
          defaultMode: 0777
      - name: timeplusd-user-config
        configMap:
          name: timeplusd-user-config
          defaultMode: 0777
  volumeClaimTemplates:
  {{- if .Values.timeplusd.storage.log.enabled }}
  - metadata:
      name: timeplusd-log
    spec:
      {{- with .Values.timeplusd.storage.log }}
      storageClassName: {{ .className }}
      accessModes:
      - {{ default .accessMode "ReadWriteOnce" }}
      volumeMode: Filesystem
      {{- with .selector }}
      selector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .size }}
      {{- end }}
    {{- end }}
  - metadata:
      name: timeplusd-history
    spec:
      {{- with .Values.timeplusd.storage.history }}
      storageClassName: {{ .className }}
      accessModes:
      - {{ default .accessMode "ReadWriteOnce" }}
      volumeMode: Filesystem
      {{- with .selector }}
      selector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .size }}
      {{- end }}
  - metadata:
      name: timeplusd-stream
    spec:
      {{- with .Values.timeplusd.storage.stream }}
      storageClassName: {{ .className }}
      accessModes:
      - {{ default .accessMode "ReadWriteOnce" }}
      volumeMode: Filesystem
      {{- with .selector }}
      selector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .size }}
      {{- end }}
{{- end }}