{{- if .Values.timeplusAppserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: timeplus-appserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timeplus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "timeplus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: timeplus-appserver
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: internal-http
    port: 8081
    protocol: TCP
    targetPort: 8081
{{- end }}